backend:
  name: github
  repo: morgansegura/segura
  branch: master
  site_domain: https://segura.llc/
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

publish_mode: editorial_workflow
media_folder: 'static/assets/images/'
public_folder: 'content/assets/'
show_preview_links: true

collections:
  # Posts
  - name: 'posts' # Used in routes, e.g., /admin/collections/blog
    label: 'Posts' # Used in the UI
    folder: 'content/blog/'
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}'
    extension: 'mdx'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - {
          label: 'Author',
          name: 'author',
          widget: 'select',
          options:
            [
              'Morgan Segura',
              'Mike Mallowe'
            ],
        }        
      - { label: 'Thumbnail', name: 'thumnail', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options:
            [
              'Blog',
              'Projects',
              'Tutorials',
              'Quick Tips',
              'Reviews',
              'Case Study',
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # Projects
  - name: 'projects' # Used in routes, e.g., /admin/collections/blog
    label: 'Projects' # Used in the UI
    folder: 'content/projects/'
    path: '{{slug}}/index'
    media_folder: 'static/assets/images/'
    public_folder: 'content/assets/'
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}'
    extension: 'mdx'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - {
          label: 'Author',
          name: 'author',
          widget: 'select',
          options:
            [
              'Morgan Segura',
              'Mike Mallowe'
            ],
        }       
      - { label: 'Thumbnail', name: 'thumnail', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options:
            [
              'Blog',
              'Projects',
              'Tutorials',
              'Quick Tips',
              'Reviews',
              'Case Study',
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
