backend:
  name: github
  repo: morgansegura/segura
  branch: master

media_folder: static/img
public_folder: src/content/img
show_preview_links: true
publish_mode: editorial_workflow

site_url: https://segura.llc
display_url: https://segura.llc

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
