backend:
  name: github
  repo: morgansegura/segura
  branch: develop
  site_domain: https://segura.llc/
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: "{{message}}"

publish_mode: editorial_workflow
media_folder: "/static/assets/images"
public_folder: "content/assets/"
show_preview_links: true
public_folder_relative: true

collections:
  # Home Page
  - name: "pages"
    label: "Pages"
    extension: "mdx"
    format: frontmatter    
    files: 
      - file: "content/pages/about/index.mdx"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about" }
          - { label: "Title", name: "title", widget: "string", default: "About Page" }
          - label: "Hero"
            name: "hero"
            widget: "object"
            collapsed: true
            fields:          
              - { label: "Hero Title", name: "heroTitle", widget: "string", required: false  }
              - { label: "Hero Alt Text", name: "heroAltText", widget: "string", required: false  }
              - { label: "Hero Image", name: "heroImage", widget: "image", required: false  }
              - { label: "Hero Body", name: "heroBody", widget: "string", required: false  }
              - label: "Hero Button"
                name: "heroButton"
                widget: "object"
                fields: 
                  - { label: "Label", name: "buttonLabel", widget: "string", required: false  }
                  - { label: "Internal Link", name: "buttonInnerLink", widget: "string", required: false  }
                  - { label: "External Link", name: "buttonOuterLink", widget: "string", required: false  }

  # Posts
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/blog/"
    path: "{{slug}}/index"
    # media_folder: ""
    # public_folder: ""
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: frontmatter
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - {
          label: "Author",
          name: "author",
          widget: "select",
          options: ["Morgan Segura"],
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          required: false,
          options:
            [
              "Article",
              "Project",
              "Tutorial",
              "Quick Tip",
              "Review",
              "Case Study",
            ],
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          default: "/content/blog/{{slug}}",
          required: false,
        }
      - {
          label: "Subheading",
          name: "subheading",
          widget: "string",
          required: false,
        }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  # Tutorials
  - name: "tutorials" # Used in routes, e.g., /admin/collections/blog
    label: "Tutorials" # Used in the UI
    folder: "content/tutorials/"
    path: "{{slug}}/index"
    # media_folder: ""
    # public_folder: ""
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    extension: "mdx"
    format: frontmatter
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - {
          label: "Author",
          name: "author",
          widget: "select",
          options: ["Morgan Segura"],
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          required: false,
          options:
            [
              "Article",
              "Project",
              "Tutorial",
              "Quick Tip",
              "Review",
              "Case Study",
            ],
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          default: "/content/tutorials/{{slug}}",
          required: false,
        }
      - {
          label: "Subheading",
          name: "subheading",
          widget: "string",
          required: false,
        }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
