backend:
  name: github
  repo: morgansegura/segura
  branch: master
  site_domain: https://segura.llc/
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: "{{message}}"

publish_mode: editorial_workflow
media_folder: "static/assets/images/"
public_folder: "content/assets/"
show_preview_links: true
public_folder_relative: true

collections:
  # Posts
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/blog/"
    path: "{{slug}}/index"
    # media_folder: ""
    # public_folder: ""
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    extension: "mdx"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - {
          label: "Author",
          name: "author",
          widget: "select",
          options: ["Morgan Segura", "Mike Mallowe"],
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          required: false,
          options:
            [
              "Article",
              "Project",
              "Tutorial",
              "Quick Tip",
              "Review",
              "Case Study",
            ],
        }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          default: "/content/blog/{{slug}}",
          required: false,
        }
      - {
          label: "Subheading",
          name: "subheading",
          widget: "string",
          required: false,
        }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
