backend:
  name: github
  repo: morgansegura/segura
  branch: master
  site_domain: https://segura.llc/

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "assets/img"
show_preview_links: true

collections:
  #Posts (English)
  - name: "posts-en" # Used in routes, e.g., /admin/collections/blog
    label: "Posts (English)" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{title}} -- {{year}}/{{month}}/{{day}}"
    extension: "en.md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "image", name: "image", widget: "image" }
      - {
          label: "Post Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          searchFields: ["author_id", "twitter"],
          valueField: "author_id",
          displayFields: ["twitter"],
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Markdown",
              "Javascript",
              "Images",
              "Gatsby",
              "Imagens",
              "Others",
              "Outros",
            ],
        }
      - {
          label: "Background",
          name: "background",
          widget: "select",
          options:
            [
              { label: "Gray", value: "#353b48" },
              { label: "Yellow", value: "#e58e26" },
              { label: "Green", value: "#079992" },
              { label: "Purple", value: "#7d4cdb" },
              { label: "Red", value: "#e74c3c" },
              { label: "Silver", value: "#bdc3c7" },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
    meta:
      - { label: "SEO Description", name: "description", widget: "text" }

  - name: "author"
    label: "Author"
    folder: "blog"
    create: true
    slug: "{{author_id}}"
    # file: "blog/author.yaml"
    extension: "md"
    format: frontmatter
    fields:
      - { label: "Name", name: "author_id", widget: "string", required: true }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Intro", name: "intro", widget: "text", required: false }
      - { label: "Bio", name: "bio", widget: "markdown", required: false }
      - { label: "Twitter", name: "twitter", widget: "string", required: false }
      - {
          label: "Facebook",
          name: "facebook",
          widget: "string",
          required: false,
        }
      - {
          label: "LinkedIn",
          name: "linkedin",
          widget: "string",
          required: false,
        }
      - { label: "Github", name: "github", widget: "string", required: false }
