export const lightTheme = {
    bgBody: 'var(--base-extra-light)',
    bgBodyLight: 'var(--base-light)',
    bgBodyDark: 'var(--base-light)',
    bgOpaque: 'rgba(250, 250, 250, .98)',
    headline: 'var(--base-dark)',
    subheadline: 'var(--base-medium-light)',
    text: 'var(--base)',
    textOffset: 'var(--base)',
    outlines: 'var(--base-light)',
    primaryColor: 'var(--primary-color)',
    primaryLightColor: 'var(--primary-light-color)',
    primaryDarkColor: 'var(--primary-dark-color)',
    secondaryColor: 'var(--secondary-color)',
    secondaryLightColor: 'var(--secondary-light-color)',
    secondaryDarkColor: 'var(--secondary-dark-color)',
}

export const darkTheme = {
    bgBody: 'var(--base)',
    bgBodyLight: 'var(--base-medium-dark)',
    bgBodyDark: 'var(--base-dark)',
    bgOpaque: 'rgba(51, 54., 71, .98)',
    headline: 'var(--base-extra-light)',
    subheadline: 'var(--base-light)',
    text: 'var(--base-medium-light)',
    textOffset: 'var(--base-medium)',
    primaryColor: 'var(--primary-color)',
    primaryLightColor: 'var(--primary-light-color)',
    primaryDarkColor: 'var(--primary-dark-color)',
    secondaryColor: 'var(--secondary-color)',
    secondaryLightColor: 'var(--secondary-light-color)',
    secondaryDarkColor: 'var(--secondary-dark-color)',
}
