export const lightTheme = {
    bgBody: 'var(--base-extra-light)',
    bgBodyLight: 'var(--base-light)',
    bgBodyDark: 'var(--base-medium-light)',
    bgOpaque: 'rgba(250, 250, 250, .98)',
    links: 'var(--base)',
    headline: 'var(--base-dark)',
    subheadline: 'var(--base-medium-light)',
    superText: 'var(--base-dark)',
    text: 'var(--base)',
    textOffset: 'var(--base)',
    outlines: 'var(--base-light)',
    outlinesDark: 'var(--base-light)',
    cards: 'white',
    accentColor: 'var(--accent-color)',
    accentLightColor: 'var(--accent-light-color)',
    accentDarkColor: 'var(--accent-dark-color)',
    ctaColor: 'var(--cta-color)',
    ctaLightColor: 'var(--cta-light-color)',
    ctaDarkColor: 'var(--cta-dark-color)',
};

export const darkTheme = {
    bgBody: 'var(--base)',
    bgBodyLight: 'var(--base-medium-dark)',
    bgBodyDark: 'var(--base-dark)',
    bgOpaque: 'rgba(51, 54, 71, .98)',
    links: 'var(--base-light)',
    headline: 'var(--base-extra-light)',
    subheadline: 'var(--base-light)',
    superText: 'var(--white)',
    text: 'var(--base-light)',
    textOffset: 'var(--base-medium)',
    outlines: 'var(--base)',
    outlinesDark: 'var(--base-medium-dark)',
    cards: 'var(--base-medium-dark)',
    accentColor: 'var(--accent-color)',
    accentLightColor: 'var(--accent-light-color)',
    accentDarkColor: 'var(--accent-dark-color)',
    ctaColor: 'var(--cta-color)',
    ctaLightColor: 'var(--cta-light-color)',
    ctaDarkColor: 'var(--cta-dark-color)',
};
